# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11a2483da657dc67275dd7fe4f6d32331510c9947daca9f1bba87cb655af5b029d8ee228e21d25ceafb836becb60337b4b71eca75cc7fa8e90aec8714937f53e

test:
  secret_key_base: 94b92d3e91819208264675c801157de397fe17011001690b229c4fa87b2bac50f7bd684a77f322f9e35b2b3409a3f769550f874e31249896f70e0a1f8cb30e5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
